export const actionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
    SET_DELETED_DATA: "SET_DELETED_DATA",
    CART_QUANTITY: "CART_QUANTITY",
    SEARCHED_PRODUCTS: "SEARCHED_PRODUCTS",
    APPLY_FILTER: "APPLY_FILTER",
    SORTED_DATA: "SORTED_DATA"
};